version: "2"
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      timezone: "Europe/Berlin"
    assignees:
      - "stnokott"
    reviewers:
      - "stnokott"
  - directory: "/"
    package-ecosystem: gomod
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Berlin"
    assignees:
      - "stnokott"
    reviewers:
      - "stnokott"
