# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

before:
  hooks:
    - go mod tidy
    - go mod verify
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    binary: app
dockers:
  - image_templates:
      - "ghcr.io/stnokott/ei-robot:latest"
      - "ghcr.io/stnokott/ei-robot:{{ .Tag }}"
    goos: linux
    goarch: amd64
    dockerfile: "{{ .Env.DOCKERFILE }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/stnokott/ei-robot:latest"
      - "ghcr.io/stnokott/ei-robot:{{ .Tag }}"
    goos: linux
    goarch: arm
    dockerfile: "{{ .Env.DOCKERFILE }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm"
  - image_templates:
      - "ghcr.io/stnokott/ei-robot:latest"
      - "ghcr.io/stnokott/ei-robot:{{ .Tag }}"
    goos: linux
    goarch: arm64
    dockerfile: "{{ .Env.DOCKERFILE }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: stnokott
    name: ei-robot
  name_template: "{{ .ProjectName }}-v{{ .Version }}"
announce:
  telegram:
    enabled: true
    chat_id: 725149271
    message_template: "{{ .ProjectName }} Version {{ .Tag }} ist veröffentlicht!"
