repos:
  - hooks:
      - id: golangci-lint
    repo: https://github.com/golangci/golangci-lint
    rev: v1.50.0
  - hooks:
      - id: go-test
      - id: go-vet
    repo: https://github.com/lietu/go-pre-commit
    rev: v0.0.1
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
  - hooks:
      - entry: go mod tidy
        id: go-mod-tidy
        language: system
        name: go-mod-tidy
        pass_filenames: false
      - entry: go fmt
        id: go-fmt
        language: system
        name: go-fmt
        pass_filenames: false
    repo: local
