repos:
  - repo: https://github.com/lietu/go-pre-commit
    rev: v0.0.1
    hooks:
      - id: go-fmt-goimports
      - id: go-test
      - id: go-vet
      - id: golangci-lint
  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go-mod-tidy
        entry: go mod tidy
        language: script
        files: '.*\.go'
